#!/usr/bin/bash -xv
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

date=$(date +"%Y");
git diff --name-only --cached --diff-filter MA | while read -r file
do
	# File doesn't exist
	if [[ ! -f $file ]]; then continue; fi
	# Check if file is reverted per a mainline branch
	git branch --list | awk '{ branch = ($1 != "*") ? $1 : $2;  if (branch !~ /[0-9]{4}|X{4}/ && Nf) { print branch}}' | while read -r branch
	do
		git merge-base --fork-point $branch 1>/dev/null;
		if [[ "$?" -eq 0 ]];
		then
			exit 1;
		fi
	done
	if [[ "$?" -ne 0 ]]; then continue; fi
	# Check if the file contains a docblock, and if so in which year the docblock occurred
	cat $file 2>/dev/null | grep -oP '@copyright[\s\w\(\)]+[0-9]{4}' 1>/dev/null;
    if [[ "$?" -ne 0 && $(grep -oP "\Q$date\E$" 1>/dev/null) ]]
    then
		echo "Un-updated docblock found in $file.";

        exit 1;
    fi
done || exit $?

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	echo "Non-ascii"
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
