#!/Users/srmes/.config/python-bin/bin/python

from colorsys import rgb_to_hls, hls_to_rgb
from sys import argv

def parse_percentage(value: str) -> float:
    return float(value.strip('%')) / 100.0

if len(argv) < 3:
  print("Usage: hex-mod [hex-target] [percentage]")
  exit(1)

hex_target = argv[1]

if hex_target.startswith('#'):
  hex_target = hex_target[1:]

r = int(hex_target[0:2],16)
g = int(hex_target[2:4],16)
b = int(hex_target[4:6],16)
a = int(hex_target[6:8],16)

percentage= parse_percentage(argv[2])

h,l,s = rgb_to_hls(r/255,g/255,b/255)
l = max(0, l * (1 - percentage))
r2,g2,b2 = hls_to_rgb(h,l,s)

print(f"adjusted rgb: {int(r2*255):02x}{int(g2*255):02x}{int(b2*255):02x}")
print(f"adjusted rgb: {int(r2*255):02x}{int(g2*255):02x}{int(b2*255):02x}{a:02x}")
print(f"alpha hex: {a:02x}")
