#!/usr/bin/bash

# Script to tar all tracked files in a git directory

set -e;

usage() {
	echo "Usage: [-h] [-d <string>] [-f <string>] [[file_name]...]" 1>&2;
	cat <<EOF
-d: Directory base path. Must be existing valid directory. Defaults to `/tmp`
-f: Base filename for archive file. Filename will be "<filename_parameter>_YYYY_mm_dd.tar.gz". Default is current git branch name
EOF

	exit 1;
}

while getopts "hf:d:" o; do
    case "${o}" in
        f)
            filename=${OPTARG}
            ;;
        d)
            dir=${OPTARG}
            ;;
        h)
            usage
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

current_branch=$(git symbolic-ref --short -q HEAD)
filename=${filename:-$current_branch};
dir=${dir:-'/tmp'}
dir="$(echo $dir | sed 's![^/]$!&/!')";

file_name="${filename}_$(date +%Y_%m_%d).tar.gz";

if [ "$#" -gt 0 ]; then
	git archive --format tar.gz -o "${dir}${file_name}" HEAD "$@";
else
	git archive --format tar.gz -o "${dir}${file_name}" HEAD
fi

echo "$dir$file_name"

exit 0;
