#!/usr/bin/bash

# Script to tar all files in the JLRCC project for a project
# Params:
# $1 -> file name
# $2 -> save directory
# $# > 2 -> [optional] filepaths to add to tar archive

set -e;

dir="$(echo $2 | sed 's![^/]$!&/!')";

file_name="$1_$(date +%Y_%m_%d).tar.gz";

#  move the start of arguments array 2 places to the right (ignore first 2 positional params)
shift 2;

if [ "$#" -gt 0 ]; then
	tar -cvzf "$dir$file_name" "$@";
else
	git archive --format tar.gz -o "$dir$file_name" HEAD
fi
