#!/usr/bin/env bash

#script to get all table names from specified mysql database
# $1: mysql database name
# $2: [optional] mysql env name (.my.cnf). Default = local

db=$1;
mysqlenv=${2:-local};

mysql --defaults-group-suffix=$mysqlenv -BAe "SHOW TABLES" $db | awk 'FNR==1{next} {print FNR, $1}'
