#!/usr/bin/env bash

sql_array="";
re='^[0-9]+$';

while IFS= read line; do
	line="$(xargs <<< $line)";

	if ! [[ line =~ re ]]
	then
		line=$(sed 's/[^[:space:],]\+/\"&\"/g' <<< $line);
		#line=$(echo $line | awk '{ printf("'%s'", $0);}');
	fi
	sql_array="$sql_array  $line"
done

echo $sql_array | tr " " ", " | awk '{ printf("(%s)\n", $0);}';
