#!/usr/bin/bash

cmd=$1
ver=$2

if [ $cmd != "en" -a $cmd != "dis" ]; then
	echo "Did not get a valid command as 1st arg: 'en' or 'dis' are allowed";
	exit 1;
fi

path="/etc/php/$ver/mods-available/xdebug.ini"

if [ $cmd == "en" -a -f "$path.dis" ]; then
	sudo mv $path{.dis,};
	sudo systemctl restart "php$ver-fpm"
elif [ $cmd == "dis" -a -f $path ]; then
	sudo mv $path{,.dis};
	sudo systemctl restart "php$ver-fpm"
fi
