#!/usr/bin/env bash

function _xdbgmod_completions()
{
	local opts;
	local verss;
	opts="en dis";
	verss=`basename -a $(find /etc/php -maxdepth 1 -mindepth 1 -type d ) | xargs echo`
	case $COMP_CWORD in
		1)
			COMPREPLY=( $(compgen -W "$opts" "${COMP_WORDS[COMP_CWORD]}"))
			;;
		2)
			COMPREPLY=( $(compgen -W "$verss" "${COMP_WORDS[COMP_CWORD]}"))
			;;
	esac;

	return 0;
}

echo "adding";
complete -F _xdbgmod_completions xdbgmod;
